app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(array('middleware'=>'web'),function() {

Route::get('/', function () {
    return view('frontend.home');
});

Route::get('page', function () {
    return view('frontend.page');
});
Route::get('about', function () {
    return view('frontend.about');
});
Route::get('contact', function () {
    return view('frontend.contact');
});
Route::get('pricing', function () {
    return view('frontend.pricing');
});

Route::get('portfolio', function () {
    return view('frontend.portfolio');
});
});
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
/**
 * Registration and login Routes. Both client and admin.
 */
Route::group(['middleware' => ['web']], function () {

    Route::post('/form', ['uses' => 'FrontEnd\OrderFormController@store', 'as' => 'form']);

    //Prices
    Route::post('/amount', ['uses' => 'FrontEnd\PricesController@store', 'as' => 'amount']);


    //Login Routes...Admin
    Route::get('/admin/login','Admin\Auth\AuthController@showLoginForm');
    Route::post('/admin/login','Admin\Auth\AuthController@postLogin');
    Route::get('/admin/logout','Admin\Auth\AuthController@getLogout');

    //Login Routes...Client
    Route::get('/client/login','Client\Auth\AuthController@showLoginForm');
    Route::post('/client/login','Client\Auth\AuthController@postLogin');
    Route::get('/client/logout','Client\Auth\AuthController@getLogout');

    // Registration Routes...Admin
    Route::get('admin/register', 'Admin\Auth\AuthController@showRegistrationForm');
    Route::post('admin/register', 'Admin\Auth\AuthController@register');

    // Registration Routes...Client
    Route::get('client/register', 'Client\Auth\AuthController@getRegister');
    Route::post('client/register', 'Client\Auth\AuthController@postRegister');

    Route::get('/admin', 'Admin\DashboardController@index');
    Route::get('/client', 'Client\DashboardController@index');



});

/**
 * Admin Routes
 */
Route::group(array('prefix'=>'admin', 'middleware'=>'web'),function() {

    Route::get('dashboard', 'Admin\DashboardController@index');
    Route::resource('users', 'Admin\UsersController');
    Route::resource('clients', 'Admin\ClientsController');
    Route::resource('payments', 'Admin\PaymentsController');
    Route::resource('orders', 'Admin\OrdersController');
    Route::resource('invoices', 'Admin\InvoicesController');
    /**
     * Settings Routes
     */
    Route::group(array('prefix'=>'settings'),function(){
        Route::resource('company', 'Admin\CompanySettingsController');
        Route::resource('invoice', 'Admin\InvoiceSettingsController');
        Route::resource('profile', 'Admin\ProfileSettingsController');
        Route::resource('order', 'Admin\OrderSettingsController');

    });
    /**
     * System Routes
     */
    Route::group(array('prefix'=>'system'),function(){
        Route::resource('payment_methods', 'Admin\PaymentMethodsController');
        Route::resource('currencies', 'Admin\CurrenciesController');
        Route::resource('assignments', 'Admin\AssignmentsController');
        Route::resource('levels', 'Admin\LevelsController');
        Route::resource('spacings', 'Admin\SpacingsController');
        Route::resource('styles', 'Admin\StylesController');
        Route::resource('subjects', 'Admin\SubjectsController');
        Route::resource('urgencies', 'Admin\UrgenciesController');
        Route::resource('prices', 'Admin\PricesController',
            ['only' => ['index', 'store']]);

        Route::resource('statuses', 'Admin\StatusController');
    });
});

/**
 * Client Routes
 */
Route::group(array('prefix'=>'client', 'middleware'=>'web'),function() {

    Route::get('dashboard', 'Client\DashboardController@index');
    Route::resource('payments', 'Client\PaymentsController');
    Route::resource('orders', 'Client\OrdersController');
    Route::resource('invoices', 'Client\InvoicesController');
    /**
     * Settings Routes
     */
    Route::group(array('prefix'=>'settings'),function(){
        Route::resource('profile', 'Client\ProfileSettingsController');
    });

});

app/Models/PaymentMethod.php
<?php

namespace App\Models;

class PaymentMethod extends BaseModel
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'payment_methods';

    /**
     * Main table primary key
     * @var string
     */
    protected $primaryKey = 'uuid';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'code', 'description'];

}

app/Http/Controllers/Admin/PaymentMethodsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\WriterController;
use App\Http\Requests\PaymentMethodRequest;
use App\Writer\Repositories\Contracts\PaymentMethodInterface;

class PaymentMethodsController extends WriterController
{
    protected $paymentMethodRepository;

    public function __construct(PaymentMethodInterface $paymentMethodRepository)
    {
        $this->middleware('admin');
        $this->paymentMethodRepository = $paymentMethodRepository;
    }

    /**
     * Display a listing of the resource.
     *     * @return Response
     */
    public function index()
    {
        $paymentMethods = $this->paymentMethodRepository->getAll();
        return view('admin.paymentmethods.index', compact('paymentMethods'));
    }

    /**
     * Show form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.paymentmethods.create');
    }

    /**
     * Store new data
     * @param PaymentMethodRequest $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(PaymentMethodRequest $request)
    {
        if($this->paymentMethodRepository->create($request->all())){
            session()->flash('success', 'Success !! Payment Method has been added.');
            return response()->json(array('success' => true, 'msg' => 'Payment Method created'), 201);
        }
        return redirect('admin/system/payment_methods');
    }

    /**
     * Show Edit Form
     * @param $uuid
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($uuid)
    {
        $paymentMethod = $this->paymentMethodRepository->getById($uuid);
        return view('admin.paymentmethods.edit', compact('paymentMethod'));
    }

    /**
     * Update data
     * @param PaymentMethodRequest $request
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(PaymentMethodRequest $request, $uuid)
    {
        if($this->paymentMethodRepository->update($request->all(), $uuid) ){
            session()->flash('success', 'Success !! Payment Method has been Updated.');
            return response()->json(array('success' => true, 'msg' => 'Payment Method Updated'), 201);
        }
        return redirect('admin/system/payment_methods');

    }

    /**
     * Delete
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($uuid)
    {
        if($uuid == 'delete_multiple'){
            $items = json_decode($_POST['items']);
            foreach($items as $fuel){
                $this->paymentMethodRepository->delete($fuel);
            }
            session()->flash('success', 'Success !! Payment Methods have been deleted.');
            return \Response::json(['success'=> true, 'message' => 'Payment Methods deleted successfully'], 200);
        }
        else{
            if($this->paymentMethodRepository->delete($uuid)){
                session()->flash('success', 'Success !! Payment Method has been deleted.');
            }else{
                session()->flash('error', 'Error !! Error deleting Payment Method. Try again.');
            }
            return redirect('admin/system/payment_methods');
        }
    }

}

resources/views/admin/paymentmethods/create.blade.php
@extends('layouts.modal')

@section('content')
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h5>Add Payment Method</h5>
            </div>
            {!! Form::open(['route' => ['admin.system.payment_methods.store'], 'class' => 'ajax-submit']) !!}
            <div class="modal-body">
                <div class="form-group">
                    {!! Form::label('name','Payment Method Name') !!}
                    {!! Form::text('name', null, ['class'=>'form-control required', 'required']) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('code','Payment Method Code') !!}
                    {!! Form::text('code', null, ['class'=>'form-control required', 'required']) !!}
                </div>


                <div class="form-group">
                    {!! Form::label('description','Payment Method Description') !!}
                    {!! Form::text('description', null, ['class'=>'form-control required', 'required']) !!}
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success"><i class="fa fa-save"></i>Save</button>
                <button type="button" data-dismiss="modal" class="btn btn-danger"><i class="fa fa-times"></i>Close</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/paymentmethods/edit.blade.php
@extends('layouts.modal')

@section('content')
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h5>Edit Payment Method</h5>
            </div>
            {!! Form::model($paymentMethod, ['route' => ['admin.system.payment_methods.update', $paymentMethod->uuid],'method'=>'PATCH', 'class'=>'ajax-submit']) !!}

            <div class="modal-body">

                <div class="form-group">
                    {!! Form::label('name','Payment Method Name') !!}
                    {!! Form::text('name', null, ['class'=>'form-control required', 'required']) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('code','Payment Method Code') !!}
                    {!! Form::text('code', null, ['class'=>'form-control required', 'required']) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('description','Payment Method Description') !!}
                    {!! Form::text('description', null, ['class'=>'form-control required', 'required']) !!}
                </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Update</button>
                <button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/paymentmethods/index.blade.php
@extends('admin.layouts.main')

@section('content')
        <!-- PAGE CONTENT -->
<div class="page-content">

    @include('admin.common.navigation_horizontal')
    @include('admin.common.system_data_breadcrumb')
    <!-- START CONTENT FRAME -->
    <div class="content-frame">

        <!-- START CONTENT FRAME TOP -->
        <div class="content-frame-top">

            <div class="pull-right">
                <button class="btn btn-default content-frame-left-toggle"><span class="fa fa-bars"></span></button>
            </div>
        </div>
        <!-- END CONTENT FRAME TOP -->

        <!-- START CONTENT FRAME LEFT -->
        <div class="content-frame-left">
            <div class="panel panel-default">

                @include('admin.common.system_navigation')


            </div>
        </div>
        <!-- END CONTENT FRAME LEFT -->

        <!-- START CONTENT FRAME BODY -->
        <div class="content-frame-body">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="page-title">
                        <h2><span class="fa fa-bars"></span> Payment Methods </h2>
                    </div>

                <!-- START DATATABLE EXPORT -->
                <div class="panel panel-default">


                    <div class="panel-heading">

                              <div class="btn-toolbar pull-right">
                               <a  class="btn btn-primary" data-toggle="ajax-modal" href="{{ route('admin.system.payment_methods.create') }}">
                                <i class="fa fa-plus-circle"></i> New Payment Method</a>

                        <div class="btn-group pull-right">
                                <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i> Export Data</button>
                            <ul class="dropdown-menu">
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'xml',escape:'false'});"><img src='{{ asset('assets\admin\img\icons/xml.png')}}' width="24"/> XML</a></li>
                                <li class="divider"></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'csv',escape:'false'});"><img src='{{ asset('assets\admin\img\icons/csv.png')}}' width="24"/> CSV</a></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'txt',escape:'false'});"><img src='{{ asset('assets\admin\img\icons/txt.png')}}' width="24"/> TXT</a></li>
                                <li class="divider"></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'excel',escape:'false'});"><img src='{{ asset('assets\admin\img\icons/xls.png')}}' width="24"/> XLS</a></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'doc',escape:'false'});"><img src='{{ asset('assets\admin\img\icons/word.png')}}' width="24"/> Word</a></li>
                                <li class="divider"></li>
                            </ul>
                        </div>
                        </div>

                    </div>
                    <div class="panel-body">


                        @if (session()->has('success'))
                            <div class="alert alert-success" id="success-alert">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif



                        <table id="customers2" class="table datatable">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Name</th>
                                <th>Code</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($paymentMethods as $paymentMethod)
                                <tr>
                                    <td>
                                        <div class="radio">
                                            <label for="{{$paymentMethod['uuid']}}"> {!! Form::checkbox('selected',$paymentMethod['uuid'],null,['class'=>'minimal select_record']) !!} </label> &nbsp;
                                        </div>
                                    </td>

                                    <td>{{ $paymentMethod->name }}</td>
                                    <td>{{ $paymentMethod->code }}</td>
                                    <td>{{ $paymentMethod->description }}</td>

                                    <td>

                                        <a  class="btn btn-success btn-sm" data-toggle="ajax-modal" href="{{ route('admin.system.payment_methods.edit', $paymentMethod->uuid) }}">
                                            <i class="fa fa-pencil"></i> Edit </a>


                                        {!! Form::open(array("method"=>"DELETE", "route" => ['admin.system.payment_methods.destroy', $paymentMethod->uuid], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                                        <a class="btn btn-danger btn-sm btn-delete"><i class="fa fa-trash-o"></i>  Delete</a>
                                        {!! Form::close() !!}

                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        {!! Form::open(array("method"=>"DELETE", "route" => ['admin.system.payment_methods.destroy', ''], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                            <a class="btn btn-danger btn-sm btn-delete-multiple"><i class="fa fa-trash-o"></i> Delete Multiple </a>
                        {!! Form::close() !!}

                    </div>
                </div>
                <!-- END DATATABLE EXPORT -->
            </div>
        </div>

        </div>



    </div>
    <!-- END PAGE CONTENT WRAPPER -->
</div>
<!-- END PAGE CONTENT -->
@endsection