app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(array('middleware'=>'web'),function() {

Route::get('/', function () {
    return view('frontend.home');
});

Route::get('page', function () {
    return view('frontend.page');
});
Route::get('about', function () {
    return view('frontend.about');
});
Route::get('contact', function () {
    return view('frontend.contact');
});
Route::get('pricing', function () {
    return view('frontend.pricing');
});

Route::get('portfolio', function () {
    return view('frontend.portfolio');
});
});
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
/**
 * Registration and login Routes. Both client and admin.
 */
Route::group(['middleware' => ['web']], function () {

    Route::post('/form', ['uses' => 'FrontEnd\OrderFormController@store', 'as' => 'form']);

    //Prices
    Route::post('/amount', ['uses' => 'FrontEnd\PricesController@store', 'as' => 'amount']);


    //Login Routes...Admin
    Route::get('/admin/login','Admin\Auth\AuthController@showLoginForm');
    Route::post('/admin/login','Admin\Auth\AuthController@postLogin');
    Route::get('/admin/logout','Admin\Auth\AuthController@getLogout');

    //Login Routes...Client
    Route::get('/client/login','Client\Auth\AuthController@showLoginForm');
    Route::post('/client/login','Client\Auth\AuthController@postLogin');
    Route::get('/client/logout','Client\Auth\AuthController@getLogout');

    // Registration Routes...Admin
    Route::get('admin/register', 'Admin\Auth\AuthController@showRegistrationForm');
    Route::post('admin/register', 'Admin\Auth\AuthController@register');

    // Registration Routes...Client
    Route::get('client/register', 'Client\Auth\AuthController@getRegister');
    Route::post('client/register', 'Client\Auth\AuthController@postRegister');

    Route::get('/admin', 'Admin\DashboardController@index');
    Route::get('/client', 'Client\DashboardController@index');



});

/**
 * Admin Routes
 */
Route::group(array('prefix'=>'admin', 'middleware'=>'web'),function() {

    Route::get('dashboard', 'Admin\DashboardController@index');
    Route::resource('users', 'Admin\UsersController');
    Route::resource('clients', 'Admin\ClientsController');
    Route::resource('payments', 'Admin\PaymentsController');
    Route::resource('orders', 'Admin\OrdersController');
    Route::resource('invoices', 'Admin\InvoicesController');
    /**
     * Settings Routes
     */
    Route::group(array('prefix'=>'settings'),function(){
        Route::resource('company', 'Admin\CompanySettingsController');
        Route::resource('invoice', 'Admin\InvoiceSettingsController');
        Route::resource('profile', 'Admin\ProfileSettingsController');
        Route::resource('order', 'Admin\OrderSettingsController');

    });
    /**
     * System Routes
     */
    Route::group(array('prefix'=>'system'),function(){
        Route::resource('payment_methods', 'Admin\PaymentMethodsController');
        Route::resource('currencies', 'Admin\CurrenciesController');
        Route::resource('assignments', 'Admin\AssignmentsController');
        Route::resource('levels', 'Admin\LevelsController');
        Route::resource('spacings', 'Admin\SpacingsController');
        Route::resource('styles', 'Admin\StylesController');
        Route::resource('subjects', 'Admin\SubjectsController');
        Route::resource('urgencies', 'Admin\UrgenciesController');
        Route::resource('prices', 'Admin\PricesController',
            ['only' => ['index', 'store']]);

        Route::resource('statuses', 'Admin\StatusController');
    });
});

/**
 * Client Routes
 */
Route::group(array('prefix'=>'client', 'middleware'=>'web'),function() {

    Route::get('dashboard', 'Client\DashboardController@index');
    Route::resource('payments', 'Client\PaymentsController');
    Route::resource('orders', 'Client\OrdersController');
    Route::resource('invoices', 'Client\InvoicesController');
    /**
     * Settings Routes
     */
    Route::group(array('prefix'=>'settings'),function(){
        Route::resource('profile', 'Client\ProfileSettingsController');
    });

});

app/Models/Client.php
<?php

namespace App\Models;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class Client extends BaseModel implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'clients';

    /**
     * Main table primary key
     * @var string
     */
    protected $primaryKey = 'uuid';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['client_name','country','phone', 'email','address', 'city',
        'state','postal_code','website','notes','status','password', 'remember_token'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function invoices(){
        return $this->hasMany('App\Models\Order');
    }
}

app/Models/Order.php
<?php
namespace App\Models;

class Order extends BaseModel
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'orders';

    /**
     * Main table primary key
     * @var string
     */
    protected $primaryKey = 'uuid';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['order_number','client_id','title', 'subject_area_id','academic_level_id', 'paid_date',
        'pages','total_cost','amount_paid','paper_type_id','deadline_date','sources', 'writing_style_id', 'paper_details', 'client_note',
        'status_id', 'code', 'spacing_id', 'urgency_id'
    ];


    //Relationships
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function client(){
        return $this->belongsTo('App\Models\Client');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function status(){
        return $this->belongsTo('App\Models\Status');
    }


    public function subject(){
        return $this->belongsTo('App\Models\Subject');
    }

    public function level(){
        return $this->belongsTo('App\Models\Level');
    }




}

app/Http/Controllers/Admin/ClientsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\WriterController;
use App\Http\Requests\ClientRequest;
use App\Writer\Repositories\Contracts\ClientInterface;

class ClientsController extends WriterController
{
    protected $clientRepository;

    public function __construct(ClientInterface $clientRepository)
    {
        $this->middleware('admin');
        $this->clientRepository = $clientRepository;
    }

    /**
     * Display a listing of the resource.
     *     * @return Response
     */
    public function index()
    {
        $clients = $this->clientRepository->getAll();
        return view('admin.clients.index', compact('clients'));
    }

    /**
     * Show form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store new data
     * @param ClientRequest $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(ClientRequest $request)
    {
        $data = array(
            'client_name'   => $request->client_name,
            'country'       => $request->country,
            'phone'         => $request->phone,
            'email'         => $request->email,
            'address'       => $request->address,
            'city'          => $request->city,
            'state'         => $request->state,
            'postal_code'   => $request->postal_code,
            'website'       => $request->website,
            'notes'         => $request->notes,
            'password'      => bcrypt($request->password)
        );

        if($this->clientRepository->create($data)){
            session()->flash('success', 'Success !! Client has been added.');
            return response()->json(array('success' => true, 'msg' => 'Client created'), 201);
        }
        return redirect('admin/clients');
    }

    /**
     * Show Edit Form
     * @param $uuid
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($uuid)
    {
        $client = $this->clientRepository->getById($uuid);
        return view('admin.clients.edit', compact('client'));
    }

    /**
     * Update data
     * @param ClientRequest $request
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(ClientRequest $request, $uuid)
    {
        $data = array(
            'client_name'   => $request->client_name,
            'country'       => $request->country,
            'phone'         => $request->phone,
            'email'         => $request->email,
            'address'       => $request->address,
            'city'          => $request->city,
            'state'         => $request->state,
            'postal_code'   => $request->postal_code,
            'website'       => $request->website,
            'notes'         => $request->notes,
            'status'        => $request->status,
            'password'      => bcrypt($request->password)
        );

        if($this->clientRepository->update($data, $uuid) ){
            session()->flash('success', 'Success !! Client has been Updated.');
            return response()->json(array('success' => true, 'msg' => 'Client Updated'), 201);
        }
        return redirect('admin/clients');

    }

    /**
     * Delete
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($uuid)
    {
        if($uuid == 'delete_multiple'){
            $items = json_decode($_POST['items']);
            foreach($items as $fuel){
                $this->clientRepository->delete($fuel);
            }
            session()->flash('success', 'Success !! Clients have been deleted.');
            return \Response::json(['success'=> true, 'message' => 'Clients deleted successfully'], 200);
        }
        else{
            if($this->clientRepository->delete($uuid)){
                session()->flash('success', 'Success !! Client has been deleted.');
            }else{
                session()->flash('error', 'Error !! Error deleting Client. Try again.');
            }
            return redirect('admin/clients');
        }
    }

}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\WriterController;
use App\Http\Requests\OrderRequest;
use App\Writer\Repositories\Contracts\OrderInterface;
use App\Writer\Repositories\Contracts\OrderSettingInterface;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Request;

class OrdersController extends WriterController
{
    protected $orderRepository;

    public function __construct(OrderInterface $orderRepository)
    {
        $this->middleware('admin');
        $this->orderRepository = $orderRepository;
    }

    /**
     * Display a listing of the resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $title = false;

        if(!empty(trim(Input::get('status')))){
            $orders = $this->orderRepository->where('status_id', Input::get('status'))->get();
            $title = true;
        }else{
            $orders = $this->orderRepository->getAll();
        }
        return view('admin.orders.index', compact('orders', 'title'));
    }

    /**
     * Show form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $clients = $this->orderRepository->clients_select();
        $subjects = $this->orderRepository->subjects_select();
        $levels = $this->orderRepository->levels_select();
        $types = $this->orderRepository->types_select();
        $spacings = $this->orderRepository->spacings_select();
        $styles = $this->orderRepository->styles_select();
        $statuses = $this->orderRepository->statuses_select();
        $urgencies = $this->orderRepository->urgencies_select();


        return view('admin.orders.create', compact('clients', 'subjects', 'levels', 'types', 'spacings', 'styles', 'statuses', 'urgencies'));
    }

    /**
     * Store new data
     * @param OrderRequest $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(OrderRequest $request)
    {
        if($this->orderRepository->create($request->all())){
            session()->flash('success', 'Success !! Order has been added.');
            return response()->json(array('success' => true, 'msg' => 'Order created'), 201);
        }
        return redirect('admin/orders');
    }

    /**
     * Show Edit Form
     * @param $uuid
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($uuid)
    {
        $order = $this->orderRepository->getById($uuid);

        $clients = $this->orderRepository->clients_select();
        $subjects = $this->orderRepository->subjects_select();
        $levels = $this->orderRepository->levels_select();
        $types = $this->orderRepository->types_select();
        $spacings = $this->orderRepository->spacings_select();
        $styles = $this->orderRepository->styles_select();
        $statuses = $this->orderRepository->statuses_select();
        $urgencies = $this->orderRepository->urgencies_select();



        return view('admin.orders.edit', compact('order', 'clients', 'subjects', 'levels', 'types', 'spacings', 'styles', 'statuses', 'urgencies'));
    }

    /**
     * Update data
     * @param OrderRequest $request
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(OrderRequest $request, $uuid)
    {
        if($this->orderRepository->update($request->all(), $uuid) ){
            session()->flash('success', 'Success !! Order has been Updated.');
            return response()->json(array('success' => true, 'msg' => 'Order Updated'), 201);
        }
        return redirect('admin/orders');

    }

    public function show($uuid)
    {
        $order = $this->orderRepository->getById($uuid);


        $clients = $this->orderRepository->clients_select();
        $subjects = $this->orderRepository->subjects_select();
        $levels = $this->orderRepository->levels_select();
        $types = $this->orderRepository->types_select();
        $spacings = $this->orderRepository->spacings_select();
        $styles = $this->orderRepository->styles_select();
        $statuses = $this->orderRepository->statuses_select();

        return view('admin.orders.show', compact('order', 'clients', 'subjects', 'levels', 'types', 'spacings', 'styles', 'statuses'));

    }

    /**
     * Delete
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($uuid)
    {
        if($uuid == 'delete_multiple'){
            $items = json_decode($_POST['items']);
            foreach($items as $fuel){
                $this->orderRepository->delete($fuel);
            }
            session()->flash('success', 'Success !! Orders have been deleted.');
            return \Response::json(['success'=> true, 'message' => 'Orders deleted successfully'], 200);
        }
        else{
            if($this->orderRepository->delete($uuid)){
                session()->flash('success', 'Success !! Order has been deleted.');
            }else{
                session()->flash('error', 'Error !! Error deleting Order. Try again.');
            }
            return redirect('admin/orders');
        }
    }

}

app/Http/Controllers/Client/DashboardController.php
<?php


namespace app\Http\Controllers\Client;


use Illuminate\Routing\Controller;

class DashboardController extends Controller
{

    public function __construct()
    {
        $this->middleware('client');
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {

        return view('client.dashboard.index');
    }

}

resources/views/client/orders/index.blade.php
@extends('client.layouts.main')

@section('content')
<!-- PAGE CONTENT -->
<div class="page-content">

    @include('admin.common.navigation_horizontal')


    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Basic</li>
    </ul>
    <!-- END BREADCRUMB -->

    <!-- PAGE TITLE -->
    <div class="page-title">
        <h2>
            <span class="fa fa-bars"></span> My Orders
            @if($title)
                <h2>  : {{$orders['0']->status['status']}}</h2>

            @endif

        </h2>
    </div>
    <!-- END PAGE TITLE -->

    <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">


        <div class="row">
            <div class="col-md-12">

                <!-- START DATATABLE EXPORT -->
                <div class="panel panel-default">





                    <div class="panel-heading">
                        <div class="btn-toolbar pull-left">

                            </div>
                              <div class="btn-toolbar pull-right">
                               <a  class="btn btn-primary" href="{{ route('client.orders.create') }}">
                                <i class="fa fa-plus-circle"></i> New Order </a>

                                  <div class="btn-group pull-right">
                                <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i> Export Data</button>
                            <ul class="dropdown-menu">
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'xml',escape:'false'});"><img src='{{ asset('assets\client\img\icons/xml.png')}}' width="24"/> XML</a></li>
                                <li class="divider"></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'csv',escape:'false'});"><img src='{{ asset('assets\client\img\icons/csv.png')}}' width="24"/> CSV</a></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'txt',escape:'false'});"><img src='{{ asset('assets\client\img\icons/txt.png')}}' width="24"/> TXT</a></li>
                                <li class="divider"></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'excel',escape:'false'});"><img src='{{ asset('assets\client\img\icons/xls.png')}}' width="24"/> XLS</a></li>
                                <li><a href="#" onClick ="$('#customers2').tableExport({type:'doc',escape:'false'});"><img src='{{ asset('assets\client\img\icons/word.png')}}' width="24"/> Word</a></li>
                                <li class="divider"></li>
                            </ul>
                        </div>
                        </div>

                    </div>
                    <div class="panel-body">


                        @if (session()->has('success'))
                            <div class="alert alert-success" id="success-alert">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif



                        <table id="customers2" class="table datatable">
                            <thead>
                            <tr>
                                <th>Order #</th>
                                <th>Title</th>
                                <th> Pages </th>
                                <th>Cost</th>
                                <th>Due</th>
                                <th> Status </th>

                                <th></th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($orders as $order)
                                <tr>
                                    <td><a href="{{ route('client.orders.show', $order->uuid) }}">{{ $order->order_number }}</a></td>
                                    <td>{{ $order->title }}</td>
                                    <td>{{ $order->pages }}</td>
                                    <td>{{ $order->total_cost }}</td>
                                    <td>{{ date('F d, Y', strtotime($order->deadline_date)) }}</td>
                                    <td>{{ $order->status['status'] }}</td>

                                    <td>
                                        <a  class="btn btn-info btn-sm" href="{{ route('client.orders.show', $order->uuid) }}">
                                            <i class="fa fa-eye"></i> View </a>

                                        <a  class="btn btn-success btn-sm" href="{{ route('client.orders.edit', $order->uuid) }}">
                                            <i class="fa fa-pencil"></i> Edit </a>


                                        {!! Form::open(array("method"=>"DELETE", "route" => ['client.orders.destroy', $order->uuid], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                                        <a class="btn btn-danger btn-sm btn-delete"><i class="fa fa-trash-o"></i>  Delete</a>
                                        {!! Form::close() !!}

                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                    </div>
                </div>
                <!-- END DATATABLE EXPORT -->
            </div>
        </div>




    </div>
    <!-- END PAGE CONTENT WRAPPER -->
</div>
<!-- END PAGE CONTENT -->
@endsection